name = "vestaflare"
main = "src/worker.ts"
compatibility_date = "2024-12-06"
compatibility_flags = ["nodejs_compat"]

[vars]
# Default environment variables
ENVIRONMENT = "development"
MCP_SERVER_NAME = "vestaflare"
MCP_SERVER_VERSION = "1.0.0"
MCP_SESSION_HEADER_NAME = "mcp-session-id"
MCP_AUTH_REQUIRED = "true"
MCP_AUTH_HEADER_NAME = "Authorization"

# Development configuration
[env.development]
vars = {
  ENVIRONMENT = "development",
  MCP_SERVER_NAME = "vestaflare",
  MCP_SERVER_VERSION = "1.0.0",
  MCP_SESSION_HEADER_NAME = "mcp-session-id",
  MCP_AUTH_REQUIRED = "true",
  MCP_AUTH_HEADER_NAME = "Authorization"
}

# Production configuration
[env.production]
vars = {
  ENVIRONMENT = "production",
  MCP_SERVER_NAME = "vestaflare",
  MCP_SERVER_VERSION = "1.0.0",
  MCP_SESSION_HEADER_NAME = "mcp-session-id",
  MCP_AUTH_REQUIRED = "true",
  MCP_AUTH_HEADER_NAME = "Authorization"
}

# Define which environment variables should be treated as secrets
# These will be populated from GitHub Secrets during deployment
[env.production.secrets]
VESTABOARD_API_BASE_URL = "VESTABOARD_API_BASE_URL"
VESTABOARD_READ_WRITE_KEY = "VESTABOARD_READ_WRITE_KEY"
MCP_API_KEY = "MCP_API_KEY"