name = "vestaflare"
main = "dist/worker.js"
compatibility_date = "2024-12-06"
compatibility_flags = ["nodejs_compat"]

# Account ID is required for Cloudflare API authentication
# This can be set via CLOUDFLARE_ACCOUNT_ID environment variable
# or by adding account_id = "your-account-id-here" directly

[vars]
# Default environment variables
ENVIRONMENT = "development"
MCP_SERVER_NAME = "vestaflare"
MCP_SERVER_VERSION = "1.0.0"
MCP_SESSION_HEADER_NAME = "mcp-session-id"
MCP_AUTH_REQUIRED = "true"
MCP_AUTH_HEADER_NAME = "Authorization"

# Development configuration
[env.development]
[env.development.vars]
ENVIRONMENT = "development"
MCP_SERVER_NAME = "vestaflare"
MCP_SERVER_VERSION = "1.0.0"
MCP_SESSION_HEADER_NAME = "mcp-session-id"
MCP_AUTH_REQUIRED = "true"
MCP_AUTH_HEADER_NAME = "Authorization"

# Production configuration
[env.production]
[env.production.vars]
ENVIRONMENT = "production"
MCP_SERVER_NAME = "vestaflare"
MCP_SERVER_VERSION = "1.0.0"
MCP_SESSION_HEADER_NAME = "mcp-session-id"
MCP_AUTH_REQUIRED = "true"
MCP_AUTH_HEADER_NAME = "Authorization"

# Secrets are handled through the GitHub Actions workflow
# and don't need to be defined in wrangler.toml