name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build worker
        run: npm run build:worker

      - name: Install Wrangler v4
        run: npm install -g wrangler@latest

      - name: Configure Cloudflare secrets
        run: |
          echo "${{ secrets.VESTABOARD_API_BASE_URL }}" | wrangler secret put VESTABOARD_API_BASE_URL --env production
          echo "${{ secrets.VESTABOARD_READ_WRITE_KEY }}" | wrangler secret put VESTABOARD_READ_WRITE_KEY --env production
          echo "${{ secrets.MCP_API_KEY }}" | wrangler secret put MCP_API_KEY --env production
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Deploy to Cloudflare Workers
        run: wrangler deploy --env production
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}