name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build worker
        run: bun run build:worker

      - name: Install Wrangler v4
        run: bun add -g wrangler@4

      - name: Set Wrangler secrets
        run: |
          echo "${{ secrets.VESTABOARD_API_BASE_URL }}" | wrangler secret put VESTABOARD_API_BASE_URL --env production
          echo "${{ secrets.VESTABOARD_READ_WRITE_KEY }}" | wrangler secret put VESTABOARD_READ_WRITE_KEY --env production
          echo "${{ secrets.MCP_API_KEY }}" | wrangler secret put MCP_API_KEY --env production
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deploy to Cloudflare Workers
        run: wrangler deploy --env production
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}