name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build worker
        run: npm run build:worker

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          environment: production
          secrets: |
            VESTABOARD_API_BASE_URL
            VESTABOARD_READ_WRITE_KEY
            MCP_API_KEY
        env:
          VESTABOARD_API_BASE_URL: ${{ secrets.VESTABOARD_API_BASE_URL }}
          VESTABOARD_READ_WRITE_KEY: ${{ secrets.VESTABOARD_READ_WRITE_KEY }}
          MCP_API_KEY: ${{ secrets.MCP_API_KEY }}